export const authConstants = {
  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  UPDATE_USER: 'AUTH_UPDATE_USER_SUCCESS',

  LOGOUT: 'AUTH_LOGOUT_SUCCESS',
};
